# Generated by Django 4.2.16 on 2024-11-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='nuevo',
            field=models.BooleanField(default=False),
        ),
    ]
