# Generated by Django 4.2.16 on 2024-11-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_nuevo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='potencia',
            field=models.CharField(max_length=50),
        ),
    ]
