# Generated by Django 4.2.16 on 2024-11-14 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_favorito'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'producto')},
        ),
    ]
